# Generated by Django 6.0.2 on 2026-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('delegate', 'Delegate'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
