# Generated by Django 6.0.2 on 2026-03-14 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_filiere_alter_user_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('approuve', 'Approuvé'), ('en_attente', 'En attente')], default='approuve', max_length=20),
        ),
        migrations.AddField(
            model_name='infosessentielles',
            name='statut',
            field=models.CharField(choices=[('approuve', 'Approuvé'), ('en_attente', 'En attente')], default='approuve', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('role_change', 'Changement de rôle'), ('approve', 'Validation')], max_length=20)),
                ('cible_type', models.CharField(max_length=100)),
                ('cible_nom', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
