# Generated by Django 6.0.2 on 2026-03-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_date_submitted_feedback_date_soumission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='api.document'),
        ),
    ]
