# Generated by Django 6.0.2 on 2026-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='niveau',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
