# Generated by Django 6.0.2 on 2026-03-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date_submitted',
            new_name='date_soumission',
        ),
        migrations.AddField(
            model_name='feedback',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('repondu', 'Répondu')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sujet',
            field=models.CharField(default='Feedback', max_length=200),
        ),
    ]
