# Generated by Django 6.0.2 on 2026-04-13 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosessentielles',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filiere'),
        ),
        migrations.AddField(
            model_name='infosessentielles',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.niveau'),
        ),
        migrations.AlterField(
            model_name='document',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filiere'),
        ),
        migrations.AlterField(
            model_name='document',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.niveau'),
        ),
    ]
