# Generated by Django 6.0.2 on 2026-04-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_infosessentielles_filiere_infosessentielles_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='categorie',
            field=models.CharField(choices=[('Cours', 'Cours'), ('TP', 'TP'), ('Autre', 'Autre')], default='Cours', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='cours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
